%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\lbukvic\OneDrive - Fakultet prometnih znanosti\Dokumenti Lucija\MATLAB\Examples\R2019b\optim\SolveMILPUsingProblemBasedApproachExample\proizvodac.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 09-Jun-2022 11:18:55

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:D4389";

% Specify column names and types
opts.VariableNames = ["Proizvodac", "Cijena_vozila", "Kilometraza", "Godina_proizvodnje"];
opts.VariableTypes = ["categorical", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Proizvodac", "EmptyFieldRule", "auto");

% Import the data
proizvodac = readtable("C:\Users\lbukvic\OneDrive - Fakultet prometnih znanosti\Dokumenti Lucija\MATLAB\Examples\R2019b\optim\SolveMILPUsingProblemBasedApproachExample\proizvodac.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts